name: build

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            BASE_URL: ${{secrets.BASE_URL}}
        steps:
            - name: 从仓库拉取源代码
              uses: actions/checkout@v3

            - name: 设置 node 版本
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: 安装依赖
              run: |
                  cd ./service
                  yarn install
                  cd ..
                  cd ./web
                  yarn install
                  cd ..

            - name: 构建
              run: |
                  mkdir ./dist
                  cd ./dist
                  mkdir ./web
                  mkdir ./service
                  mkdir ./proxy
                  mkdir ./daemon
                  cd ..
                  cd ./service
                  yarn build
                  cd ..
                  cd ./proxy
                  yarn build
                  cd ..
                  cd ./daemon
                  yarn build
                  cd ..
                  cd ./web
                  echo 'VITE_HTTP_BASE_URL=${{secrets.BASE_URL}}' >> .env
                  yarn build
                  cd ..
                  cp ./package.json ./dist
                  cp -r ./service/dist/out ./dist/service
                  cp -r ./proxy/dist/out ./dist/proxy
                  cp -r ./daemon/dist/out ./dist/daemon
                  cp -r ./web/dist ./dist/web
                  cp ./web/package.json ./dist/web

            - name: 上传前端文件
              uses: actions/upload-artifact@v3
              with:
                  name: frontend-build
                  path: dist/web/

            - name: 上传后端文件
              uses: actions/upload-artifact@v3
              with:
                  name: service-build
                  path: dist/service

            - name: 上传图片代理节点文件
              uses: actions/upload-artifact@v3
              with:
                  name: proxy-build
                  path: dist/proxy

            - name: 上传守护进程文件
              uses: actions/upload-artifact@v3
              with:
                  name: daemon-build
                  path: dist/daemon
